name: CI-CD Docker

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Construir la imagen
      - name: Build Docker image
        run: docker build -t juandarodram/devops-starter:latest .

      # 3️⃣ Ejecutar tests
      - name: Run tests
        run: docker run --rm juandarodram/devops-starter:latest npm test

      # 4️⃣ Login en Docker Hub (usa secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Push a Docker Hub
      - name: Push image
        run: docker push juandarodram/devops-starter:latest