name: CI-CD Auto Deploy AWS

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t juandarodram/devops-starter:latest .

      - name: Run tests
        run: docker run --rm juandarodram/devops-starter:latest npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push juandarodram/devops-starter:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.191.102.82
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull juandarodram/devops-starter:latest
            sudo docker stop devops-app || true
            sudo docker rm devops-app || true
            sudo docker run -d -p 80:3000 --name devops-app juandarodram/devops-starter:latest